package com.quizmaster.util;


import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.*;
import java.util.Objects;
import java.util.Properties;

public class DBConnection {
    private String host;
    private String sid;
    private String port;
    private String driver;
    private String user;
    private String password;


    public Connection getConnection(){

        Connection con = null;

        if(getProperties()){

            String url = "jdbc:oracle:"+driver+":@"+host+":"+port+":"+sid;
            System.out.println("Database URL: "+url);

            try {
                Class.forName("oracle.jdbc.driver.OracleDriver");   //ojdbc driver class loader
                System.out.println("OJDBC driver load success");    //for checking
                con = DriverManager.getConnection(url,user,password);
                //con.close();
                System.out.println("Database Connection established");

            } catch (Exception e) {
                e.printStackTrace();
                System.out.println("OJDBC driver load failure");    //for checking
            }

        } else {
            System.out.println("Database Connection not established");
        }
        return con;
    }


    private boolean getProperties(){

        Properties properties = new Properties();
        InputStream input = null;
        boolean success=false; //checks whether the DBProperties file gets read or not

        try {
            String rootPath = Objects.requireNonNull(Thread.currentThread().getContextClassLoader().getResource("")).getPath(); //requireNonNull autogenerated cause .getPath() may return NULL
            System.out.println("RootPath: "+rootPath);   //for checking
            String dbPropPath = rootPath + "DB.properties";
            System.out.println("DBProperties resource path: "+dbPropPath); //for checking
            input = new FileInputStream(dbPropPath);
            properties.load(input);

            host=properties.getProperty("host");
            sid=properties.getProperty("sid");
            port=properties.getProperty("port");
            driver=properties.getProperty("driver");
            user=properties.getProperty("user");
            password=properties.getProperty("password");

            System.out.println(host+" "+sid+" "+port+" "+driver+" "+user+" "+password);     //for checking
            success=true;
            input.close();  //close the input stream

        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Oops!! DB.properties file needs to be configured in resource directory" +
                    "against keys host,sid,port,driver,user and password");
        }
        System.out.println("DBProperties file gets loaded: "+success);    //for checking
        return success;

    }
}
